version: '3.8'
services:
  runpg_db:
    container_name: runpg_db
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  runpg_api:
    restart: always
    build:
      context: ./
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - '5000:5000'
    depends_on:
      - runpg_db
