version: '3.8'
services:
  postgres:
    container_name: runpg_db
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
