version: '3.8'
services:
  runpg_db:
    container_name: runpg_db
    image: postgres:14.2
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  runpg_db_test:
    container_name: runpg_db_test
    image: postgres:14.2
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
